<script src="{{asset('assets/js/plugin.bundle.min.js')}}"></script>
<script src="{{asset('assets/js/bootstrap.bundle.min.js')}}"></script>
<script src="{{asset('assets/api/jqueryvalidate/jquery.validate.min.js')}}"></script>
<script src="{{asset('assets/api/apexcharts/apexcharts.js')}}"></script>
<script src="{{asset('assets/api/apexcharts/scriptcharts.js"')}}"></script>
<script src="{{asset(' assets/api/pace/pace.js')}}"></script>
<script src="{{asset('assets/api/mcustomscrollbar/jquery.mCustomScrollbar.concat.min.js')}}"></script>
<script src="{{asset('assets/api/datatable/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('assets/api/editor/classic.ckeditor.js')}}"></script>
<script src="{{asset('assets/js/sweetalert.js')}}"></script>
<script src="{{asset('assets/js/sweetalert1.js')}}"></script>
<script src="{{asset('assets/js/script.bundle.js')}}"></script>
<script src="{{asset('assets/js/scripts.js')}}"></script>