<table>
    <tr>
        <th>Fecha</th>
        <th>Tipo</th>
        <th>Desde</th>
        <th>Hacia</th>
        <th>Entrada</th>
        <th>Salida</th>
        <th>Stock</th>
        <th>Bultos</th>
    </tr>
    @foreach ($movimientos as $m)
    <tr>
        <td>{{\Carbon\Carbon::parse($m->created_at)->format('d/m/Y')}}</td>
        <td>{{$m->movement->type}}</td>
        <td>{{$m->movement->From($m->movement->type)}}</td>
        <td>{{$m->movement->To($m->movement->type)}}</td>
        <td>{{$m->entry}}</td>
        <td>{{$m->egress}}</td>
        <td>{{$m->balance}}</td>
        <td>{{$m->bultos}}</td>
    </tr>
    @endforeach
</table>